import { Resp } from './resp.model';
export interface ICategory {
  name: string;
  isOpen?: boolean;

  // isSelected: boolean;
  siblings?: ICategory[];
  isParent: boolean;
  children?: ICategory[];
}
// Generated by https://quicktype.io

export interface Categories extends Resp {
  categories: Category[];
}

export type CategoryDirection = 1 | 2;

export interface Category {
  category_id: number;
  name: string;
  image: string;
  siblings?: Category[];
  children: Category[];
  isOpen?: boolean;
  direction?: CategoryDirection;
  // only for add new;
  // parent_category_id?: number;
}
