// Generated by https://quicktype.io

export interface ClientDetail {
  rc: number;
  message: string;
  client_id: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_num: string;
  address: string;
  comment: string;
  num_of_orders: number;
  order_total: number;
  client_message_prefix: string;
}
