import { Resp } from './resp.model';
// Generated by https://quicktype.io

export interface DashboardData extends Resp {
  open_orders: number;
  total_ordes: number;
  total_ordes_cost: number;
  total_clients: number;
  returning_clients: number;
  clients_per_month: { [key: string]: number };
  orders_per_month: { [key: string]: number };
}
