import { ISelect } from './../utils/from-obj';
import { Resp } from './resp.model';
import { ValidValues } from './owner-item-detail.model';
// Generated by https://quicktype.io

export interface ItemValidValues extends Resp {
  units: { [key: string]: string };
  currency: string;
  promotion_templates: { [key: string]: string };
  is_pro_account: number;
  expand_advanced_info: number;
  expand_promotion: number;
  is_deletable: number;
  options: [{ [key: string]: string }];
}

export interface ItemConvertedValidValues extends Modify<ItemValidValues, {
  units: ISelect[];
  promotion_templates: ISelect[],
  options: ISelect[],
  stores: any[],
}> { }
