// Generated by https://quicktype.io

export interface OpenOrders {
  rc: number;
  message: string;
  orders: OpenOrder[];
}

export interface OpenOrder {
  order_id: number;
  client_name: string;
  phone_num: string;
  address: string;
  order_time: string;
  num_of_items: number;
  order_total: number;
  is_new: number;
  delivery_time: string;
  order_delivery_cent: number;
}
