import { Resp } from './resp.model';
import { ItemValidValues, ItemConvertedValidValues } from './item-valid.value.model';
// Generated by https://quicktype.io


export interface OwnerItemDetail {
  rc: number;
  message: string;
  item_id: number;
  name: string;
  unit: number;
  description: string;
  catalog_number: string;
  price: number;
  sale_price: number;
  member_price: number;
  available_amount: number;
  limit_purchase_amount: number;
  alert_below: number;
  link_to_manufacturer_site: string;
  show_carousel: number;
  show_sidebar: number;
  promo_template: number;
  is_in_stock: boolean;
  promo_image: string;
  categories: Category[];
  images: any[];
  valid_values: ValidValues | ItemConvertedValidValues;
  options: string;
  stores: any[];
}

export interface Category {
  category_id: number;
  name: string;
}

export interface ValidValues {
  units: { [key: string]: string };
  currency: string;
  promotion_templates: { [key: string]: string };
  is_pro_account: number;
  expand_advanced_info: number;
  expand_promotion: number;
  is_deletable: number;
}
